USE [master]
GO

/****** Object:  Database [NikovBikeShopDB]    Script Date: 8.3.2016 ã. 23:43:44 ÷. ******/
CREATE DATABASE [NikovBikeShopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NikovBikeShopDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\NikovBikeShopDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NikovBikeShopDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\NikovBikeShopDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NikovBikeShopDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NikovBikeShopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NikovBikeShopDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NikovBikeShopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NikovBikeShopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NikovBikeShopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NikovBikeShopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET RECOVERY FULL 
GO

ALTER DATABASE [NikovBikeShopDB] SET  MULTI_USER 
GO

ALTER DATABASE [NikovBikeShopDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NikovBikeShopDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NikovBikeShopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NikovBikeShopDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NikovBikeShopDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NikovBikeShopDB] SET  READ_WRITE 
GO


